<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Run</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-04-09T18:14:55</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>32a8028e-b4f2-4b30-a6ce-ad2a54de0ae6</testSuiteGuid>
   <testCaseLink>
      <guid>eb4a466a-b8f4-45e2-a1a0-dd0d286edfd8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/test01</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14743001-590f-460c-bf51-da7015e65804</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b223de3-7d64-4494-a955-f31449462981</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
